---

version: "3.9"

services:
  telegram_bot:
    env_file: backend/telegram-bot/.env
    build:
      context: backend/telegram-bot

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

volumes:
  redis_data:
