---

version: "3.9"

services:
  api:
    env_file: .env
    build:
      context: backend/api
    ports:
      - "8080:8080"

  telegram_bot:
    env_file: .env
    build:
      context: backend/telegram-bot

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

volumes:
  redis_data:
