---

version: "3.9"

services:
  # Backend

  api:
    env_file: .env
    build:
      context: backend/api
    ports:
      - "8080:8080"

  telegram_bot:
    env_file: .env
    build:
      context: backend/telegram-bot

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

  # Frontend

  nginx:
    image: nginx:1.21
    volumes:
      - ./frontend/interface:/usr/share/nginx/html
    ports:
      - "8081:80"

volumes:
  redis_data:
